### ISSUE TITLE
TODO assembled version

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/Scylla-PCB-Plate#2]
- [ ] same rgb footprint as dilemma, just longer pads
- [ ] use 0402 or 0201 diodes, in clusters - eg. sod523 (C122862)
- [ ] new edge cuts
